### ISSUE TITLE
Connection to Soundpad failed

### ISSUE THREAD

**Issue by Hidduh** [sonodima/soundpad-web#1]
I just cloned the repo and I'm trying to launch it through Windows Terminal, but when I browse to the URL it returns an error that a connection to Soundpad cannot be established.

```
x [soundpad-web] (main)$ npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /mnt/c/Users/x/Desktop/soundpad-web/node_modules/next-pwa/register.js
> [PWA] Service worker: /mnt/c/Users/x/Desktop/soundpad-web/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Build in develop mode, cache and precache are mostly disabled. This means offline support is disabled, but you can continue developing other functions in service worker.
> [PWA] Compile server
event - compiled client and server successfully in 6.5s (129 modules)
wait  - compiling / (client and server)...
warn  - GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
warn  - GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
wait  - compiling /api/getSounds...
warn  - GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
Attempting connection to Soundpad pipe
Error: connect ENOENT \\.\pipe\sp_remote_control
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\sp_remote_control'
}
Connection result: false
```

The webpage itself returns a 501 on /api/getSounds. Above happens every time I browse to the URL.

**Comment by sonodima** [comment]
It seems that it can't connect to SoundPad's pipe.

Is SoundPad running in the background?
Also, note that the remote control is only allowed in the full version of the soundboard.

[SoundPad Remote Control](https://leppsoft.com/soundpad/help/manual/tutorial/rc/#remote-control)


Edit: I can confirm that the application is still working correctly on a clean Windows installation.

**Comment by Hidduh** [comment]
I'm using the full version bought on Steam. I tried calling Soundpad through the command line and that worked fine, cloning the repo and running it through Terminal still returns an error when trying to connect to the Soundpad pipe. Is there an option you have to enable in order to get the pipe working or am I missing something?

**Comment by sonodima** [comment]
This is weird, you shouldn't need to enable anything in the program.

Could you please provide your SoundPad version, Windows build and Node version?

**Comment by Hidduh** [comment]
Sure thing:

Soundpad: 3.4.1 (Steam edition)
Windows: Windows 10 Pro 21H2 (OS build 19044.2006)
Node: v16.17.0 (LTS), npm 8.19.1

**Comment by Hidduh** [comment]
FYI - this issue no longer persists. I have absolutely no idea what exactly fixed it, but i'm finally able to connect to Soundpad. 🎉
