### ISSUE TITLE
[Enhancement] Batch script that opens the server and soundpad simultaneously

### ISSUE THREAD

**Issue by DanielHeringer** [sonodima/soundpad-web#2]
Hello, I did a batch script that opens the server and soundpad simultaneously, and I wanted to share with you guys and if you think it's worthy, add it to the code. 
In the root of the project I added this batch file and created a shortcut for it in my desktop.
`@echo off`
`start "" "steam://rungameid/629520"`
`for /f "delims=[] tokens=2" %%a in ('ping -4 -n 1 %ComputerName% ^| findstr [') do set NetworkIP=%%a`
`echo Network IP: %NetworkIP%`
`npm run dev`
`if %errorlevel% neq 0 pause`

1. It opens soundpad from steam using URL
2. Give my private IP so I know what address its using
3. Opens soundpad web server

As I'm just sharing my case, it's possible that as not everybody uses soundpad from steam it needs some adjustment to work with any source.

**Comment by sonodima** [comment]
Thank you for your contribution, I'm going to test the script to check if it's reliable enough as soon as I have a bit of free time.

If everything goes to plan I'll add it to the repository 👍🏼

**Comment by sonodima** [comment]
I added it with the latest commit!
